DB_NAME = 'te'
USERS_COLLECTION_NAME = 'users'
PLACES_COLLECTION_NAME = 'places'

ACTIONS_LIST = ('Park', 'Cinema', 'Trip to the sea', 'English lesson', 'Work', 'Chill out')
STATUSES_LIST = ('angry', 'upset', 'feels good', 'feels good', 'friendly')
RELATIONSHIPS_LIST = ('good', 'good', 'good', 'middle', 'middle', 'bad')

FOOD_LIST = (
    'acorn squash',
    'alfalfa',
    'artichoke',
    'arugula',
    'asparagus',
    'avocado',
    'bamboo shoots',
    'basil',
    'beans',
    'beets',
    'bell pepper',
    'black-eyed peas',
    'broccoli',
    'Brussels sprouts',
    'capers',
    'carrot',
    'cauliflower',
    'celeriac',
    'celery',
    'chard',
    'chick peas',
    'Chinese cabbage',
    'chives',
    'collard greens',
    'cress',
    'cucumber',
    'daikon',
    'dandelion greens',
    'eggplant',
    'endive',
    'fava bean',
    'fennel',
    'garlic',
    'ginger',
    'gourd',
    'greenbean',
    'greens',
    'hot chile peppers',
    'iceberg lettuce',
    'jicama',
    'kale',
    'kohlrabi',
    'leek',
    'lentils',
    'lettuce',
    'Lima bean',
    'maize',
    'mung bean',
    'mushroom',
    'mustard greens',
    'okra',
    'olive',
    'onion',
    'parsley',
    'parsnip',
    'pattypan squash',
    'pea',
    'peapod',
    'peanut',
    'peppers',
    'pickle',
    'potato',
    'pumpkin',
    'radicchio',
    'radish',
    'rhubarb',
    'rocket',
    'romaine',
    'rutabaga',
    'salad',
    'salsa',
    'scallion',
    'seaweed',
    'shallot',
    'sorrel',
    'soybean',
    'spinach',
    'sprouts',
    'salsify',
    'spuds',
    'squash',
    'string bean',
    'succotash',
    'sweet potato',
    'Swiss chard',
    'taro',
    'tomatillo',
    'tomato',
    'tuber',
    'turnip',
    'vegetable',
    'wasabi',
    'water chestnut',
    'watercress',
    'yam',
    'zucchini'
)
