CREATE TABLE TBL1 (pktest NUMBER(5), vctest VARCHAR2(15) NOT NULL)
TABLESPACE DARK_PINK_LAB STORAGE (INITIAL 50K);
INSERT INTO TBL1 VALUES (1, 'TBL1_1');
CREATE TABLE TBL2 (pktest NUMBER(5), vctest VARCHAR2(15) NOT NULL)
TABLESPACE FAST_BLACK_LAKE STORAGE (INITIAL 50K);
INSERT INTO TBL2 VALUES (1, 'TBL2_1');
