CREATE USER STUD IDENTIFIED BY PASSWORDO DEFAULT TABLESPACE DARK_PINK_LAB QUOTA
UNLIMITED ON DARK_PINK_LAB;
GRANT CREATE SESSION TO STUD;
GRANT CREATE TABLE TO STUD;
GRANT CREATE PROCEDURE TO STUD;
GRANT CREATE TRIGGER TO STUD;
GRANT CREATE VIEW TO STUD;
GRANT CREATE SEQUENCE TO STUD;
GRANT CREATE VIEW TO STUD;
GRANT DELETE ANY TABLE TO STUD;
GRANT DROP ANY TABLE TO STUD;
GRANT DROP ANY PROCEDURE TO STUD;
GRANT DROP ANY TRIGGER TO STUD;
GRANT DROP ANY VIEW TO STUD;
GRANT ALTER ANY TABLE TO STUD;
GRANT ALTER ANY TABLE TO STUD;
GRANT ALTER ANY PROCEDURE TO STUD;
GRANT ALTER ANY TRIGGER TO STUD;
commit;
ALTER USER STUD QUOTA UNLIMITED ON FAST_BLACK_LAKE;
connect STUD
